from __future__ import annotations

import torch

from moe_lab.craft_moe.route_coreset import (
    box_coordinate_descent,
    delta_patched_hidden,
    enumerate_best_fits,
    higher_quantile,
    minimum_k_from_kl,
    ranked_original_coefficients,
    reconstruct_routed,
    relative_routed_error,
    rescaled_rank1_coefficients,
    routed_target,
)


def test_delta_patch_reproduces_official_teacher_exactly_for_original_route() -> None:
    generator = torch.Generator().manual_seed(7)
    outputs = torch.randn(5, 6, 8, generator=generator, dtype=torch.bfloat16)
    weights = torch.softmax(torch.randn(5, 6, generator=generator), dim=-1)
    teacher = torch.randn(5, 8, generator=generator, dtype=torch.bfloat16)
    original = routed_target(outputs, weights)

    patched = delta_patched_hidden(teacher, original, original)

    assert patched.dtype == teacher.dtype
    assert torch.equal(patched, teacher)


def test_exact_nnls_oracle_finds_two_atom_nonnegative_representation() -> None:
    # Every selected expert lies in the cone generated by atoms a and b, so the
    # full six-expert target must have an exact non-negative two-atom solution.
    a = torch.tensor([1.0, 0.0, 0.5, -0.25], dtype=torch.float64)
    b = torch.tensor([0.0, 1.0, -0.5, 0.75], dtype=torch.float64)
    atoms = torch.stack((a, b, 2 * a, 2 * b, a + b, 2 * a + b))
    outputs = torch.stack((atoms, 1.5 * atoms, 0.75 * atoms))
    weights = torch.tensor(
        [
            [0.10, 0.15, 0.20, 0.10, 0.25, 0.20],
            [0.05, 0.25, 0.10, 0.20, 0.15, 0.25],
            [0.20, 0.05, 0.15, 0.25, 0.10, 0.25],
        ],
        dtype=torch.float64,
    )

    fits = enumerate_best_fits(outputs, weights, max_k=5, box_iterations=64)
    nnls_two = fits["nnls"][2]

    assert torch.all(nnls_two.coefficients >= 0)
    assert torch.all(nnls_two.subset_mask.sum(dim=1) <= 2)
    assert torch.all(nnls_two.squared_error < 1e-10)
    reconstructed = reconstruct_routed(outputs, nnls_two.coefficients)
    assert torch.allclose(reconstructed, routed_target(outputs, weights), atol=1e-8)


def test_box_coordinate_descent_obeys_bounds() -> None:
    gram = torch.eye(2, dtype=torch.float64).unsqueeze(0)
    rhs = torch.tensor([[3.0, -1.0]], dtype=torch.float64)
    upper = torch.tensor([[2.0, 2.0]], dtype=torch.float64)

    solution = box_coordinate_descent(gram, rhs, upper)

    assert torch.equal(solution, torch.tensor([[2.0, 0.0]], dtype=torch.float64))


def test_ranked_and_rescaled_rank1_choose_largest_router_weight() -> None:
    weights = torch.tensor([[0.05, 0.45, 0.15, 0.35]], dtype=torch.float64)
    outputs = torch.eye(4, dtype=torch.float64).unsqueeze(0)

    ranked = ranked_original_coefficients(weights, 2)
    rescaled = rescaled_rank1_coefficients(outputs, weights)

    assert torch.equal(
        ranked, torch.tensor([[0.0, 0.45, 0.0, 0.35]], dtype=torch.float64)
    )
    assert torch.equal(rescaled.nonzero()[:, 1], torch.tensor([1]))
    assert relative_routed_error(outputs, weights, ranked).item() > 0


def test_minimum_k_and_higher_empirical_quantile_use_conservative_rules() -> None:
    kl_by_k = {
        1: torch.tensor([0.0005, 0.0020, 0.0040, 0.0100]),
        2: torch.tensor([0.0004, 0.0008, 0.0030, 0.0090]),
        3: torch.tensor([0.0003, 0.0007, 0.0009, 0.0080]),
    }

    minimum = minimum_k_from_kl(kl_by_k, threshold=0.001)

    assert torch.equal(minimum, torch.tensor([1, 2, 3, 4]))
    assert higher_quantile(minimum, 0.75) == 3.0


def test_input_validation_rejects_mismatched_shapes() -> None:
    outputs = torch.zeros(2, 6, 4)
    weights = torch.zeros(2, 5)

    try:
        enumerate_best_fits(outputs, weights)
    except ValueError as error:
        assert "router_weights" in str(error)
    else:
        raise AssertionError("expected a shape validation error")
