#!/usr/bin/env python3
"""Static no-payload/no-device PH1 Intel execution implementation preflight."""
from __future__ import annotations
import ast,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S=ROOT/'scripts/streamq5_moe';R=ROOT/'reports/streamq5_moe'
BACK=S/'het_next_l0_ph1_intel_execution_r0_backend.py';RUN=S/'run_het_next_l0_ph1_intel_execution_r0.py';VER=S/'verify_het_next_l0_ph1_intel_execution_r0.py';PR=R/'HET_NEXT_L0_PH1_INTEL_EXECUTION_R0_PREREGISTRATION_2026-08-14.md';LOCK=R/'het_next_l0_ph1_intel_execution_r0_lock.json';OUT=R/'het_next_l0_ph1_intel_execution_r0';RESULT=R/'het_next_l0_ph1_intel_execution_r0_static_preflight.json';COM=R/'het_next_l0_ph1_intel_compile_r2a';CPU=R/'het_next_l0_ph1_cpu_freeze_r2'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 l=json.loads(LOCK.read_text());bt=ast.parse(BACK.read_text());rt=ast.parse(RUN.read_text());calls={n.func.attr for n in ast.walk(bt) if isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and n.func.attr.startswith('cl')};allowed={'clGetPlatformIDs','clGetDeviceIDs','clGetDeviceInfo','clGetExtensionFunctionAddressForPlatform','clCreateContext','clCreateCommandQueue','clCreateProgramWithBinary','clBuildProgram','clCreateKernel','clEnqueueNDRangeKernel','clFinish','clReleaseKernel'};calls|={n.value for n in ast.walk(bt) if isinstance(n,ast.Constant) and n.value in {'clReleaseProgram','clReleaseCommandQueue','clReleaseContext'}}
 obs={'backend_sha256':sha(BACK),'runner_sha256':sha(RUN),'verifier_sha256':sha(VER),'preflight_sha256':sha(Path(__file__)),'prereg_sha256':sha(PR),'compile_commit_sha256':sha(COM/'commit.json'),'compile_result_sha256':sha(COM/'result.json'),'compile_binary_sha256':sha(COM/'intel_program.bin'),'compile_source_sha256':sha(COM/'intel_source.cl'),'cpu_commit_sha256':sha(CPU/'commit.json'),'cpu_verification_sha256':sha(R/'het_next_l0_ph1_cpu_freeze_r2_independent_verification.json')}
 text=BACK.read_text();tests={'closed_self_bound':l.get('execution_open') is False and l.get('audit_token')=='PENDING' and all(l.get(k)==v for k,v in obs.items()),'compiled_artifact':obs['compile_binary_sha256']=='8b57db279fbb1d7d8df17ebab5cfb54203ef8da8cc31df2d136650820548f629' and (COM/'intel_program.bin').stat().st_size==186352 and obs['compile_source_sha256']=='f1b3ccdae6d202ed210810e3cd419f726ea89ffa8fba0c84df5c2bfca3a84d21','cardinality_source':all(x in text for x in ('len(BUFFER_TABLE)!=14','sum(len(x[1]) for x in ARGUMENT_MAPS)!=18','len(LAUNCHES)!=4','release_attempts')),'opencl_call_surface':calls==allowed,'no_copy_buffer_calls':not any(x in text for x in ('clCreateBuffer','clEnqueueRead','clEnqueueWrite','clEnqueueCopy','clEnqueueMigrate','cl_mem ')),'runner_schema':all(x in {n.name for n in rt.body if isinstance(n,ast.FunctionDef)} for x in ('verify_bundle','archive','recover','authorize','payload','gates','main')),'output_absent':not OUT.exists(),'result_absent':not RESULT.exists()}
 out={'kind':'ph1_intel_execution_r0_static_preflight','tests':tests,'pass':all(tests.values()),'passed':sum(tests.values()),'total':len(tests),'payload_reads':0,'device_calls':0}
 if RESULT.exists():raise FileExistsError(RESULT)
 RESULT.write_text(json.dumps(out,sort_keys=True,indent=2)+'\n');print(json.dumps(out,indent=2));return 0 if out['pass'] else 3
if __name__=='__main__':raise SystemExit(main())
