#!/usr/bin/env python3
"""Comprehensive static/no-forward R4 preflight; expected blocked before audited prompt revision."""
import ast,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S=ROOT/'scripts/streamq5_moe';R=ROOT/'reports/streamq5_moe';RUN=S/'run_port80b_t0q5r4_auditable_quality.py';VER=S/'verify_port80b_t0q5r4_auditable_quality.py';LOCK=R/'port80b_t0q5r4_runner_lock.json';VL=R/'port80b_t0q5r4_verifier_lock.json';PR=R/'PORT80B_T0Q5R4_AUDITABLE_EXECUTION_PREREGISTRATION_2026-08-13.md';SCI=R/'PORT80B_T0Q5R3_REAL_LAYER0_NUMERICAL_QUALITY_PREREGISTRATION_2026-08-13.md';CODEC=S/'port80b_t0q5r3_codec_contract.py';GEN=S/'generate_port80b_t0q5r1_prompts.py';R3=S/'run_port80b_t0q5r3_real_layer0_quality.py';PL=R/'port80b_t0q5r4_prompt_lock.json';D=ROOT/'reports/runs/streamq5_moe/port80b_t0q5r4_auditable_quality'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def funcs(path):return {n.name for n in ast.walk(ast.parse(Path(path).read_text())) if isinstance(n,ast.FunctionDef)}
def main():
 l=json.loads(LOCK.read_text());v=json.loads(VL.read_text());a={'runner_sha256':sha(RUN),'verifier_sha256':sha(VER),'verifier_lock_sha256':sha(VL),'execution_prereg_sha256':sha(PR),'science_prereg_sha256':sha(SCI),'codec_sha256':sha(CODEC),'generator_sha256':sha(GEN),'r3_source_sha256':sha(R3),'prompt_lock_sha256':sha(PL) if PL.exists() else '__ABSENT_PENDING_IMPLEMENTATION_AUDIT__'};rs=RUN.read_text();vs=VER.read_text();rf=funcs(RUN);vf=funcs(VER);checks={'all_hash_bindings':all(l.get(k)==x for k,x in a.items()) and v['verifier_sha256']==a['verifier_sha256'],'output_absent':not D.exists(),'prompt_present':PL.exists(),'lock_will_fail_absent_prompt':not PL.exists() and l['prompt_lock_sha256']=='__ABSENT_PENDING_IMPLEMENTATION_AUDIT__','runner_phases':{'guard','capture','reference','build','parse','graph','safe_reject','controls','q5','quarantine','fail'}.issubset(rf),'verifier_replay':{'decode','graph','reference','q5','metric','commit'}.issubset(vf),'verifier_independent':'importlib' not in vs and 'port80b_t0q5r3_codec_contract' not in vs and 'run_port80b' not in vs,'exact_order':all(x in rs for x in ('top_k_pos,token_idx=torch.where(mask[ei])','gate*ss','gate*qs','torch.add(res,','register_forward_pre_hook(residual)')),'transactions':all(x in rs for x in ("open('xb')",'os.fsync','os.replace','quarantine','failed_attempts','.inprogress')),'resources':all(x in rs for x in ('16*2**30','2*2**30','12*2**30','4*2**30','MAX_ART')),'prompt_runtime':all(x in rs for x in ('g.generate()','prompt disjointness','len(x[\'token_ids\'])!=16')),'forbidden_physical_preflight':all(x not in Path(__file__).read_text() for x in ('safe_open(','from_pretrained(','torch.cuda','reference()','q5()'))};out={'kind':'t0q5r4_static_preflight','pass':all(checks.values()),'expected_blocked':not checks['prompt_present'],'checks':checks,'physical_actions':{'prompt_generation':False,'tokenizer':False,'model':False,'shard':False,'forward':False,'bank':False,'gpu':False}};print(json.dumps(out,indent=2));return 0 if out['pass'] else 3
if __name__=='__main__':raise SystemExit(main())
