#!/usr/bin/env python3
"""Closed no-device/no-payload R7 closed preflight for corrected independent verifier."""
from __future__ import annotations
import ast,copy,hashlib,inspect,json,struct,zlib
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[2];S=ROOT/'scripts/streamq5_moe';R=ROOT/'reports/streamq5_moe'
RUN=S/'run_het_next_l0_ph1_intel_execution_r7.py';BACK=S/'het_next_l0_ph1_intel_execution_r6_backend.py';COMMON=S/'het_next_l0_ph1_intel_execution_r6_common.py';VER=S/'verify_het_next_l0_ph1_intel_execution_r7.py';OLDPRE=S/'preflight_het_next_l0_ph1_intel_execution_r6.py';R0B=S/'het_next_l0_ph1_intel_execution_r0_backend.py';R0R=S/'run_het_next_l0_ph1_intel_execution_r0.py'
PR=R/'HET_NEXT_L0_PH1_INTEL_EXECUTION_R7_PREREGISTRATION_2026-08-14.md';LOCK=R/'het_next_l0_ph1_intel_execution_r7_lock.json';OLDLOCK=R/'het_next_l0_ph1_intel_execution_r6_lock.json';OLDAUD=R/'HET_NEXT_L0_PH1_INTEL_EXECUTION_R6_INDEPENDENT_SOURCE_AUDIT_2026-08-14.md';DIAG=R/'HET_NEXT_L0_PH1_INTEL_EXECUTION_R6_PREFLIGHT_CRASH_DIAGNOSIS_2026-08-14.md';P1LOCK=R/'het_next_l0_ph1_intel_execution_r6p1_lock.json';P1PRE=S/'preflight_het_next_l0_ph1_intel_execution_r6p1.py';P1AUD=R/'HET_NEXT_L0_PH1_INTEL_EXECUTION_R6P1_INDEPENDENT_SOURCE_AUDIT_2026-08-14.md';P1RESULT=R/'het_next_l0_ph1_intel_execution_r6p1_static_preflight.json';P1DIAG=R/'HET_NEXT_L0_PH1_INTEL_EXECUTION_R6P1_ORACLE_OUTPUTS_NEGATIVE_DIAGNOSIS_2026-08-14.md';OUT=R/'het_next_l0_ph1_intel_execution_r7';RESULT=R/'het_next_l0_ph1_intel_execution_r7_static_preflight.json'
VERIFIER_MUTATION_EVIDENCE={}
def fs(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def loader_call_names(trees):
 return {n.func.attr if isinstance(n.func,ast.Attribute) else n.func.id for t in trees for n in ast.walk(t) if isinstance(n,ast.Call) and isinstance(n.func,(ast.Attribute,ast.Name)) and (n.func.attr if isinstance(n.func,ast.Attribute) else n.func.id) in {'WinDLL','CDLL','LoadLibrary','LoadLibraryEx'}}
def decode_fixture_record(common,rec,shape):
 r,c=shape;f=common.HEADER.unpack(rec[:64]);codes=rec[64:655424];sc=rec[655424:671808]
 if len(rec)!=675840 or f[:9]!=(b'SQ5M',1,0,50,f[4],5,r,c,128) or (zlib.crc32(sc,zlib.crc32(codes))&0xffffffff)!=f[11]:raise ValueError('fixture_record')
 a=np.frombuffer(codes,np.uint8).reshape(-1,5).astype(np.uint64);words=sum(a[:,i]<<(8*i) for i in range(5));fields=((words[:,None]>>(5*np.arange(8,dtype=np.uint64)))&31)
 if np.any(fields>30):raise ValueError('field31')
 q=fields.astype(np.int16).reshape(r,c)-15;scale=common.b2f(np.frombuffer(sc,'<u2')).reshape(r,c//128).repeat(128,axis=1)
 return common.f2b(q.astype(np.float32)*scale).astype(np.uint16)

def codec_oracle_fixtures(old,common,verify):
 if not old.codec_oracle_fixtures.__module__.endswith('r6'):return False
 zeros=bytes(512*2048*2);field_word=sum(15<<(5*i) for i in range(8));codes=field_word.to_bytes(5,'little')*(512*2048//8);sc=(b'\x80\x3f')*(512*2048//128);crc=zlib.crc32(sc,zlib.crc32(codes))&0xffffffff;head=common.HEADER.pack(b'SQ5M',1,0,50,0,5,512,2048,128,len(codes),len(sc),crc,bytes(28));expected_record=head+codes+sc+bytes(4032);spec0=('fixture',0,(512,2048),(0,0),hashlib.sha256(zeros).hexdigest(),hashlib.sha256(codes).hexdigest(),hashlib.sha256(sc).hexdigest(),hashlib.sha256(expected_record).hexdigest())
 if common.record(spec0,zeros)!=expected_record:return False
 src=np.zeros((512,2048),np.float32);src[0,:8]=np.asarray([-1,-.5,-.25,0,.25,.5,.75,1],np.float32);words=common.f2b(src).astype('<u2').tobytes();v=common.b2f(np.frombuffer(words,'<u2')).reshape(512,2048);bl=v.reshape(512,16,128);m=np.max(np.abs(bl),axis=-1,keepdims=True);scale=np.where(m>0,np.asarray(m/np.float32(15),np.float32),np.float32(1));q=np.where(m>0,np.clip(np.rint(np.asarray(bl/scale,np.float32)),-15,15),0).astype(np.int16);fld=(q+15).astype(np.uint64).reshape(-1,8);packed=np.bitwise_or.reduce(fld<<(np.arange(8,dtype=np.uint64)*5),axis=1);nz_codes=np.stack([(packed>>(8*i))&255 for i in range(5)],axis=1).astype(np.uint8).tobytes();nz_sc=common.f2b(scale.reshape(-1)).astype('<u2').tobytes();nz_crc=zlib.crc32(nz_sc,zlib.crc32(nz_codes))&0xffffffff;nz_head=common.HEADER.pack(b'SQ5M',1,0,50,0,5,512,2048,128,len(nz_codes),len(nz_sc),nz_crc,bytes(28));nz_rec=nz_head+nz_codes+nz_sc+bytes(4032);nz_spec=('fixture',0,(512,2048),(0,0),hashlib.sha256(words).hexdigest(),hashlib.sha256(nz_codes).hexdigest(),hashlib.sha256(nz_sc).hexdigest(),hashlib.sha256(nz_rec).hexdigest())
 if q[0,0,:8].tolist()!=[-15,-7,-4,0,4,7,11,15] or common.record(nz_spec,words)!=nz_rec:return False
 vr,decoded=verify.codec(words,nz_spec)
 if vr!=nz_rec or decoded.shape!=(512,2048) or decoded[0,:8].tolist()!=common.f2b(q.reshape(512,2048).astype(np.float32)*common.b2f(np.frombuffer(nz_sc,'<u2')).reshape(512,16).repeat(128,axis=1))[0,:8].tolist():return False
 vectors=[(0x3f800000,0x3f800000,0,0x3f800000),(0x3f000000,0x40000000,0,0x3f800000),(0xbf800000,0x3f000000,0x3f800000,0x3f000000)]
 if any(verify.fma(a,b,c)!=e for a,b,c,e in vectors):return False
 w512=np.zeros((1,512),np.uint16);x512=np.zeros(512,np.uint16);w512[0,:8]=0x3f80;x512[:8]=0x3f80
 w2048=np.zeros((1,2048),np.uint16);x2048=np.zeros(2048,np.uint16);w2048[0,:8]=0x3f80;x2048[:8]=0x3f80
 return verify.linear(w512,x512).tolist()==[0x4100] and verify.linear(w2048,x2048).tolist()==[0x4100] and verify.mul(0x3f80,0x4000)==0x4000

def write_after_loop_negative(verify):
 src=inspect.getsource(verify.linear)
 if '\n  out[row]=rb(lanes[0])' not in src:raise RuntimeError('corrected_assignment_missing')
 badsrc=src.replace('\n  out[row]=rb(lanes[0])','\n out[row]=rb(lanes[0])',1);ns={'np':np,'fma':verify.fma,'add':verify.add,'rb':verify.rb};exec(badsrc,ns)
 evidence=verify.linear_all_row_sentinel(ns['linear'])
 return {'pass':not evidence['pass'],'mutated_source_sha256':hashlib.sha256(badsrc.encode()).hexdigest(),'sentinel':evidence}

def bundle_mutations_r7(verify):
 result=(json.dumps({'kind':'ph1_intel_execution_r7','positive':True},sort_keys=True,separators=(',',':'))+'\n').encode();row={'name':'result.json','bytes':len(result),'sha256':hashlib.sha256(result).hexdigest()};manifest={'kind':'ph1_intel_execution_r7_manifest','files':[row]};mb=(json.dumps(manifest,sort_keys=True,separators=(',',':'))+'\n').encode();commit={'kind':'ph1_intel_execution_r7_commit','manifest_sha256':hashlib.sha256(mb).hexdigest(),'result_sha256':hashlib.sha256(result).hexdigest()};names={'result.json','manifest.json','commit.json'}
 if not verify.verify_bundle_contract(result,manifest,commit,names,len(result)+len(mb)+100):return False
 bad=[(result,{**manifest,'kind':'wrong'},commit,names,1),(result,manifest,{**commit,'result_sha256':'0'*64},names,1),(result,manifest,commit,names|{'extra'},1),(result,manifest,commit,names,16*2**20+1),(b'{}\n',manifest,commit,names,1)]
 return all(not verify.verify_bundle_contract(*x) for x in bad)

def verifier_mutations(verify,common,lock):
 old=(verify.BUFF,verify.ARGS,verify.LAUNCH,verify.STAGE,verify.SPECS)
 try:
  verify.BUFF=(('gate_record',675840),('up_record',675840),('down_record',675840),('natural_input',4096),('silu_lut',131072),('gate',1024),('up',1024),('silu',1024),('activation',1024),('down',4096),('gate_counters',2048),('up_counters',2048),('activation_counters',2048),('down_counters',8192));verify.ARGS=(('gate_linear',('gate_record','natural_input','gate','gate_counters')),('up_linear',('up_record','natural_input','up','up_counters')),('activation',('gate','up','silu_lut','silu','activation','activation_counters')),('down_linear',('down_record','activation','down','down_counters')));verify.LAUNCH=[('gate_linear',4096,256),('up_linear',4096,256),('activation',512,256),('down_linear',16384,256)]
  inp=bytes(4096);lut=bytes(131072);records={};specs=[]
  for ordinal,name in enumerate(('gate','up','down')):
   rows,cols=((512,2048) if name!='down' else (2048,512));word=(sum(15<<(5*i) for i in range(8))&~31)|16;codes=word.to_bytes(5,'little')*(rows*cols//8);sc=(b'\x80\x3f')*(rows*cols//128);crc=zlib.crc32(sc,zlib.crc32(codes))&0xffffffff;head=verify.HEADER.pack(b'SQ5M',1,0,50,ordinal,5,rows,cols,128,len(codes),len(sc),crc,bytes(28));rec=head+codes+sc+bytes(4032);spec=(name,ordinal,(rows,cols),(0,0),'unused',hashlib.sha256(codes).hexdigest(),hashlib.sha256(sc).hexdigest(),hashlib.sha256(rec).hexdigest());specs.append(spec);records[name]=rec
  specs=tuple(specs);verify.SPECS=specs;weights={s[0]:decode_fixture_record(common,records[s[0]],s[2]) for s in specs};iw=np.zeros(2048,np.uint16);qg=verify.linear(weights['gate'],iw);qu=verify.linear(weights['up'],iw);qs=np.zeros(512,np.uint16);qa=np.zeros(512,np.uint16);qd=verify.linear(weights['down'],qa)
  out={'gate':qg.astype('<u2').tobytes(),'up':qu.astype('<u2').tobytes(),'silu':qs.astype('<u2').tobytes(),'activation':qa.astype('<u2').tobytes(),'down':qd.astype('<u2').tobytes(),'gate_counters':struct.pack('<'+'I'*512,*([1]*512)),'up_counters':struct.pack('<'+'I'*512,*([1]*512)),'activation_counters':struct.pack('<'+'I'*512,*([1]*512)),'down_counters':struct.pack('<'+'I'*2048,*([1]*2048))}
  expected_lengths={'gate':1024,'up':1024,'silu':1024,'activation':1024,'down':4096,'gate_counters':2048,'up_counters':2048,'activation_counters':2048,'down_counters':8192};weight_binding=all(np.all(w.reshape(w.shape[0],-1,8)[:,:,0]==0x3f80) and np.all(w.reshape(w.shape[0],-1,8)[:,:,1:]==0) for w in weights.values())
  schema_ok=(weights['gate'].shape==(512,2048) and weights['up'].shape==(512,2048) and weights['down'].shape==(2048,512) and weight_binding and len(inp)==4096 and {k:len(v) for k,v in out.items()}==expected_lengths and verify.BUFF==old[0] and dict(verify.BUFF)==dict(expected_lengths|{'gate_record':675840,'up_record':675840,'down_record':675840,'natural_input':4096,'silu_lut':131072}) and verify.ARGS==old[1] and verify.LAUNCH==old[2])
  if not schema_ok:return False
  verify.STAGE={k:hashlib.sha256(out[k]).hexdigest() for k in ('gate','up','silu','activation','down')};buff=verify.BUFF;pointers={n:4096*(i+1) for i,(n,_) in enumerate(buff)};identity={'name':'Intel(R) Arc(TM) Pro 140T GPU (32GB)','vendor':'Intel(R) Corporation','driver':'32.0.101.8517','pci':'0000:00:02.0'};ledger=[{'op':'identity','identity':identity},{'op':'context_create','pointer':101},{'op':'queue_create','pointer':102},{'op':'program_create_binary','pointer':103}]+[{'op':'kernel_create','pointer':104+i} for i in range(4)]+[{'op':'host_usm_allocate','name':n,'bytes':z,'alignment':4096,'pointer':pointers[n],'base':pointers[n],'queried_size':z,'type':0x4197} for n,z in buff]
  for n,d in [('gate_record',records['gate']),('up_record',records['up']),('down_record',records['down']),('natural_input',inp),('silu_lut',lut)]:ledger.append({'op':'cpu_direct_write','name':n,'sha256':hashlib.sha256(d).hexdigest()})
  ledger +=[{'op':'initialize','name':n,'value':'ff'} for n in ('gate','up','silu','activation','down')]+[{'op':'initialize','name':n,'value':'00'} for n in ('gate_counters','up_counters','activation_counters','down_counters')]
  for kernel,names in verify.ARGS:
   for i,n in enumerate(names):ledger.append({'op':'set_pointer_arg','kernel':kernel,'index':i,'name':n,'pointer':pointers[n]})
  for i,(k,g,l) in enumerate(verify.LAUNCH):
   if i==0:ledger.append({'op':'resource_sample','stage':'backend_entry','available':2*2**30,'peak_wset':12*2**30})
   ledger +=[{'op':'resource_sample','stage':'pre_launch:'+str(i),'available':2*2**30,'peak_wset':12*2**30},{'op':'enqueue','kernel':k,'global':g,'local':l,'event_requested':False},{'op':'resource_sample','stage':'post_launch:'+str(i),'available':2*2**30,'peak_wset':12*2**30}]
  ledger +=[{'op':'resource_sample','stage':'pre_finish','available':2*2**30,'peak_wset':12*2**30},{'op':'finish'},{'op':'resource_sample','stage':'post_finish','available':2*2**30,'peak_wset':12*2**30}]
  for n in ('gate','up','silu','activation','down','gate_counters','up_counters','activation_counters','down_counters'):ledger.append({'op':'cpu_direct_read','name':n,'bytes':dict(buff)[n],'sha256':hashlib.sha256(out[n]).hexdigest(),'after_finish':True})
  rel=['usm:'+x[0] for x in reversed(buff)]+['kernel:down_linear','kernel:activation','kernel:up_linear','kernel:gate_linear','program','queue','context'];ledger +=[{'op':'release','name':n,'attempt_index':i,'attempted':True,'owned_before':True,'code':0,'exception':None,'owned_after':False} for i,n in enumerate(rel)]+[{'op':'cleanup','cleanup_complete':True,'release_attempts':21,'live_owned_resources':0,'live_resource_names':[]},{'op':'resource_sample','stage':'post_cleanup','available':2*2**30,'peak_wset':12*2**30}]
  for qi,x in enumerate(y for y in ledger if y.get('op')=='resource_sample'):x.update({'qpc_ns':qi+1,'rss':1,'telemetry_error':None})
  observed={k:fs(v) for k,v in verify.PROVENANCE.items()};prepared=(specs,inp,lut,records,weights,lock,observed);oldspec=common.SPECS
  try:common.SPECS=specs;controls=common.controls(records,inp,lut)
  finally:common.SPECS=oldspec
  own_apis=['clCreateContext','clCreateCommandQueue','clCreateProgramWithBinary']+['clCreateKernel']*4+sum((['clHostMemAllocINTEL']+['clGetMemAllocInfoINTEL']*3 for _ in range(14)),[])+['clSetKernelArgMemPointerINTEL']*18+['clMemFreeINTEL']*14;ownership=[{'api':api,'attempted':True,'returned':([101,102,103,104,105,106,107][i] if i<7 else (pointers[buff[(i-7)//4][0]] if api=='clHostMemAllocINTEL' else 0)),'registered_pending':i<7 or api=='clHostMemAllocINTEL','exception':None} for i,api in enumerate(own_apis)];creates=[x for x in ownership if x['api'] in ('clCreateContext','clCreateCommandQueue','clCreateProgramWithBinary','clCreateKernel')];hosts=[x for x in ownership if x['api']=='clHostMemAllocINTEL'];frees=[x for x in ownership if x['api']=='clMemFreeINTEL'];names=['context','queue','program']+[f'kernel:{n}' for n in ('gate_linear','up_linear','activation','down_linear')];[x.update({'object_name':n,'object_pointer':x['returned'],'promoted':True,'release_name':n}) for x,n in zip(creates,names)];[x.update({'object_name':'usm:'+n,'object_pointer':pointers[n],'promoted':True,'release_name':'usm:'+n}) for x,(n,_z) in zip(hosts,buff)];[x.update({'object_name':'usm:'+n,'object_pointer':pointers[n],'promoted':True,'release_name':'usm:'+n}) for x,(n,_z) in zip(frees,reversed(buff))]
  ev={'outputs':{k:v.hex() for k,v in out.items()},'ledger':ledger,'identity':identity,'ownership_ledger':ownership,'extension_counts':{'clHostMemAllocINTEL':14,'clMemFreeINTEL':14,'clSetKernelArgMemPointerINTEL':18,'clGetMemAllocInfoINTEL':42},'forbidden_calls':{k:0 for k in ('clCreateBuffer','clEnqueueReadBuffer','clEnqueueWriteBuffer','clEnqueueCopyBuffer','clEnqueueMigrateMemObjects','clEnqueueMemAdviseINTEL')},'telemetry_errors':[]};base={'positive':True,'status':'intel_execution_positive','claim':'one real expert/input Intel correctness component only','evidence':ev,'controls':controls,'authorization':{'lock_sha256':fs(verify.LOCK),'observed':observed},'resource':{'sampling_claim':'retained phase samples, not continuous peak monitor','start_available':16*2**30,'start_peak_wset':12*2**30,'post_payload_available':2*2**30,'post_payload_peak_wset':12*2**30,'final_available':2*2**30,'final_peak_wset':12*2**30,'post_serialize_available':2*2**30,'post_serialize_peak_wset':12*2**30,'peak_retained_wset':12*2**30},'gates':{'fixture':True},'stage_hashes':verify.STAGE}
  baseline=verify.verify_dict(base,prepared);VERIFIER_MUTATION_EVIDENCE.clear();VERIFIER_MUTATION_EVIDENCE.update({'baseline_checks':baseline,'baseline_false_names':[k for k,v in baseline.items() if not v]})
  if not all(baseline.values()):return False
  alloc0=next(i for i,x in enumerate(ledger) if x.get('op')=='host_usm_allocate');arg0=next(i for i,x in enumerate(ledger) if x.get('op')=='set_pointer_arg');launch0=next(i for i,x in enumerate(ledger) if x.get('op')=='enqueue');read0=next(i for i,x in enumerate(ledger) if x.get('op')=='cpu_direct_read');release0=next(i for i,x in enumerate(ledger) if x.get('op')=='release');sample0=next(i for i,x in enumerate(ledger) if x.get('op')=='resource_sample');geti0=next(i for i,x in enumerate(ownership) if x.get('api')=='clGetMemAllocInfoINTEL');setp0=next(i for i,x in enumerate(ownership) if x.get('api')=='clSetKernelArgMemPointerINTEL')
  mutation_names=['getinfo_status','setptr_status','ownership_missing','ownership_duplicate','ownership_return','ownership_pending','ownership_pointer','identity','control_missing','output','pointer_alias','alignment','usm_type','usm_base','arg_pointer','launch_geometry','launch_event','read_order','release_order','release_owned','release_code','cleanup','provenance','resource_summary','resource_order','resource_peak','forbidden_api','stage_hash']
  mutations=[lambda x:x['evidence']['ownership_ledger'][geti0].__setitem__('returned',-5),lambda x:x['evidence']['ownership_ledger'][setp0].__setitem__('returned',-5),lambda x:x['evidence']['ownership_ledger'].pop(),lambda x:x['evidence']['ownership_ledger'].append(copy.deepcopy(x['evidence']['ownership_ledger'][0])),lambda x:x['evidence']['ownership_ledger'][0].__setitem__('returned',999),lambda x:x['evidence']['ownership_ledger'][0].__setitem__('registered_pending',False),lambda x:x['evidence']['ownership_ledger'][0].__setitem__('object_pointer',999),lambda x:x['evidence']['identity'].__setitem__('pci','wrong'),lambda x:x['controls'].pop(),lambda x:x['evidence']['outputs'].__setitem__('gate','00'),lambda x:x['evidence']['ledger'][alloc0].__setitem__('pointer',x['evidence']['ledger'][alloc0+1]['pointer']),lambda x:x['evidence']['ledger'][alloc0].__setitem__('alignment',128),lambda x:x['evidence']['ledger'][alloc0].__setitem__('type',0),lambda x:x['evidence']['ledger'][alloc0].__setitem__('base',0),lambda x:x['evidence']['ledger'][arg0].__setitem__('pointer',0),lambda x:x['evidence']['ledger'][launch0].__setitem__('global',1),lambda x:x['evidence']['ledger'][launch0].__setitem__('event_requested',True),lambda x:x['evidence']['ledger'][read0].__setitem__('after_finish',False),lambda x:x['evidence']['ledger'][release0].__setitem__('attempt_index',99),lambda x:x['evidence']['ledger'][release0].__setitem__('owned_before',False),lambda x:x['evidence']['ledger'][release0].__setitem__('code',-1),lambda x:x['evidence']['ledger'][-2].__setitem__('cleanup_complete',False),lambda x:x['authorization']['observed'].__setitem__('runner_sha256','0'*64),lambda x:x['resource'].__setitem__('peak_retained_wset',12*2**30+1),lambda x:x['evidence']['ledger'][sample0].__setitem__('stage','wrong'),lambda x:x['evidence']['ledger'][sample0].__setitem__('peak_wset',12*2**30+1),lambda x:x['evidence']['forbidden_calls'].__setitem__('clCreateBuffer',1),lambda x:x['stage_hashes'].__setitem__('gate','0'*64)]
  rejected=[]
  for name,mutate in zip(mutation_names,mutations,strict=True):
   m=copy.deepcopy(base);mutate(m)
   if all(verify.verify_dict(m,prepared).values()):return False
   rejected.append(name)
  VERIFIER_MUTATION_EVIDENCE.update({'mutation_names':mutation_names,'rejected_mutations':rejected})
  return True
 finally:verify.BUFF,verify.ARGS,verify.LAUNCH,verify.STAGE,verify.SPECS=old

def main():
 import sys;sys.path.insert(0,str(S));import preflight_het_next_l0_ph1_intel_execution_r6 as old;import het_next_l0_ph1_intel_execution_r6_common as common;import het_next_l0_ph1_intel_execution_r6_backend as back;import run_het_next_l0_ph1_intel_execution_r7 as run;import run_het_next_l0_ph1_intel_execution_r6 as run6;import verify_het_next_l0_ph1_intel_execution_r7 as verify
 lock=json.loads(LOCK.read_text());observed={k:fs(v) for k,v in verify.PROVENANCE.items()};chain={'r7_preflight_sha256':fs(Path(__file__)),'r7_prereg_sha256':fs(PR),'r6p1_lock_sha256':fs(P1LOCK),'r6p1_preflight_sha256':fs(P1PRE),'r6p1_audit_sha256':fs(P1AUD),'r6p1_result_sha256':fs(P1RESULT),'r6p1_diagnosis_sha256':fs(P1DIAG),'r6_lock_sha256':fs(OLDLOCK),'r6_original_preflight_sha256':fs(OLDPRE),'r6_audit_sha256':fs(OLDAUD),'r6_crash_diagnosis_sha256':fs(DIAG)};trees={p:ast.parse(p.read_text()) for p in (RUN,BACK,COMMON,VER,Path(__file__),OLDPRE,P1PRE,R0B,R0R)};imports={n.module for t in trees.values() for n in ast.walk(t) if isinstance(n,ast.ImportFrom)}|{a.name for t in trees.values() for n in ast.walk(t) if isinstance(n,ast.Import) for a in n.names};forbidden={'clCreateBuffer','clEnqueueReadBuffer','clEnqueueWriteBuffer','clEnqueueCopyBuffer','clEnqueueMigrateMemObjects','clEnqueueMemAdviseINTEL'};calls={n.func.attr for t in trees.values() for n in ast.walk(t) if isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute)};static_trees=[trees[p] for p in (Path(__file__),OLDPRE,P1PRE,COMMON,VER)];static_imports={n.module for t in static_trees for n in ast.walk(t) if isinstance(n,ast.ImportFrom)}|{a.name for t in static_trees for n in ast.walk(t) if isinstance(n,ast.Import) for a in n.names};loader_calls=loader_call_names(static_trees);fake_rejected=loader_call_names([ast.parse("WinDLL('OpenCL.dll')")])=={'WinDLL'};literal_accepted=not loader_call_names([ast.parse("x='WinDLL(\\\"OpenCL.dll\\\")'")])
 sentinel=verify.linear_all_row_sentinel();bad_sentinel=write_after_loop_negative(verify);actual_mutations=verifier_mutations(verify,common,lock);checks={'hash_bindings':all(lock.get(k)==v for k,v in observed.items()) and all(lock.get(k)==v for k,v in chain.items()),'closed':lock.get('kind')=='ph1_intel_execution_r7_lock' and lock.get('execution_open') is False and lock.get('audit_token')=='PENDING' and not OUT.exists() and not RESULT.exists(),'cardinalities':len(back.BUFFER_TABLE)==14 and sum(z for _,z in back.BUFFER_TABLE)==2185216 and sum(len(x) for _,x in back.ARGUMENT_MAPS)==18 and len(back.LAUNCHES)==4,'extension_abi':set(back.EXTENSION_ABI)=={'clHostMemAllocINTEL','clMemFreeINTEL','clSetKernelArgMemPointerINTEL','clGetMemAllocInfoINTEL'},'no_device_static':not ({'pyopencl','cupy','torch','safetensors','transformers'}&static_imports) and not loader_calls,'ast_no_device_nonvacuous':fake_rejected and literal_accepted,'forbidden_call_surface':not (forbidden&calls),'synthetic_22_controls':old.synthetic_controls(common),'codec_fma_width8_full_shapes':codec_oracle_fixtures(old,common,verify),'package_commit_mutations':old.package_mutations(run),'bundle_mutations':bundle_mutations_r7(verify),'cleanup_faults_21':old.cleanup_faults(back),'atomic_create_ownership':old.atomic_ownership_faults(back),'transaction_failure':old.transaction_sim(run6),'production_lifecycle':old.lifecycle_sim(run6),'all_row_linear_sentinel':sentinel['pass'],'write_after_loop_negative':bad_sentinel['pass'],'actual_verifier_mutations_full_shapes':actual_mutations};out={'kind':'ph1_intel_execution_r7_static_preflight','checks':checks,'pass':all(checks.values()),'passed':sum(checks.values()),'total':len(checks),'no_payload_compiler_device':True,'supersedes_r6p1_result':fs(P1RESULT),'linear_sentinel':sentinel,'write_after_loop_negative':bad_sentinel,'verifier_fixture_evidence':VERIFIER_MUTATION_EVIDENCE}
 if RESULT.exists():raise FileExistsError(RESULT)
 RESULT.write_text(json.dumps(out,sort_keys=True,indent=2)+'\n');print(json.dumps(out,indent=2));return 0 if out['pass'] else 3
if __name__=='__main__':raise SystemExit(main())

