#!/usr/bin/env python3
"""No-forward T0Q5-R3 preflight. Intentionally blocked until audited revision prompt lock."""
import ast,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S=ROOT/'scripts/streamq5_moe';R=ROOT/'reports/streamq5_moe';RUN=S/'run_port80b_t0q5r3_real_layer0_quality.py';VER=S/'verify_port80b_t0q5r3_real_layer0_quality.py';CODEC=S/'port80b_t0q5r3_codec_contract.py';LOCK=R/'port80b_t0q5r3_runner_lock.json';VL=R/'port80b_t0q5r3_verifier_lock.json';PL=R/'port80b_t0q5r3_prompt_lock.json';D=ROOT/'reports/runs/streamq5_moe/port80b_t0q5r3_real_layer0_quality'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 l=json.loads(LOCK.read_text());v=json.loads(VL.read_text());source=RUN.read_text();tree=ast.parse(source);names={n.name for n in ast.walk(tree) if isinstance(n,ast.FunctionDef)};checks={'runner_bound':l['runner_sha256']==sha(RUN),'verifier_bound':l['verifier_sha256']==sha(VER) and v['verifier_sha256']==sha(VER),'codec_bound':l['codec_sha256']==sha(CODEC),'output_absent':not D.exists(),'prompt_lock_present':PL.exists(),'phase_functions':{'capture','reference','build_bank','graph','controls_for_prompt','q5','failure'}.issubset(names),'official_where_order':"top_k_pos,token_idx=torch.where(mask[ei])" in source,'prehook_residual':"register_forward_pre_hook(residual)" in source,'verifier_independent':'importlib' not in VER.read_text() and 'port80b_t0q5r3_codec_contract' not in VER.read_text(),'transactions_and_failure':all(x in source for x in (".inprogress","os.replace","open('xb')","os.fsync"))};out={'kind':'port80b_t0q5r3_no_forward_preflight','pass':all(checks.values()),'blocked_expected_before_audited_revision':not checks['prompt_lock_present'],'checks':checks,'physical_actions':{'tokenizer':False,'model':False,'shard_scan':False,'forward':False,'bank':False,'gpu':False}};print(json.dumps(out,indent=2));return 0 if out['pass'] else 3
if __name__=='__main__':raise SystemExit(main())
