#!/usr/bin/env python3
"""PH1 Intel execution R1: provenance, controls, resources and exact ledger gates."""
from __future__ import annotations
import argparse,hashlib,json,os,sys,traceback,uuid
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S=ROOT/'scripts/streamq5_moe';sys.path.insert(0,str(S));R=ROOT/'reports/streamq5_moe'
import het_next_l0_ph1_intel_execution_r1_backend as backend
import het_next_l0_ph1_intel_execution_r1_common as common
import run_het_next_l0_ph1_intel_execution_r0 as base
OUT=R/'het_next_l0_ph1_intel_execution_r1';FAILED=R/'het_next_l0_ph1_intel_execution_r1_failed_attempts';QUAR=R/'het_next_l0_ph1_intel_execution_r1_quarantine';LOCK=R/'het_next_l0_ph1_intel_execution_r1_lock.json';PR=R/'HET_NEXT_L0_PH1_INTEL_EXECUTION_R1_PREREGISTRATION_2026-08-14.md';PRE=S/'preflight_het_next_l0_ph1_intel_execution_r1.py';VER=S/'verify_het_next_l0_ph1_intel_execution_r1.py';AUD=R/'HET_NEXT_L0_PH1_INTEL_EXECUTION_R0_INDEPENDENT_SOURCE_AUDIT_2026-08-14.md';COM=R/'het_next_l0_ph1_intel_compile_r2a';CVER=R/'het_next_l0_ph1_intel_compile_r2a_independent_verification.json';CREPORT=R/'HET_NEXT_L0_PH1_INTEL_COMPILE_R2A_INDEPENDENT_VERIFICATION_REPORT_2026-08-14.md';CPU=R/'het_next_l0_ph1_cpu_freeze_r2';CPUVER=R/'het_next_l0_ph1_cpu_freeze_r2_independent_verification.json';CPUREPORT=R/'HET_NEXT_L0_PH1_CPU_FREEZE_R2_INDEPENDENT_VERIFICATION_REPORT_2026-08-14.md';GEN=S/'generate_het_next_l0_ph1_cpu_freeze.py';ACK='PH1_INTEL_EXECUTION_R1_AFTER_SOURCE_AND_STATIC_PREFLIGHT_GO'
EXPECTED={'audit_sha256':'1b701f0f5c4a4aab466688ded74da304e1d240006c37fff55855e6b120f036bf','compile_commit_sha256':'c9f9ab3838d9d3d4ddd6e16a18f7989c16061901f08e046987081d9d975a152a','compile_result_sha256':'ac7c90e15c71cf2a481004f78954e9d78631078d3e08893d3f716120345df5cc','compile_manifest_sha256':'9be3e584a4bda6b827ef1f536ccbbff42f6b2bbd4cbf998a530e7133f0a369ff','compile_build_log_sha256':'6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d','compile_binary_sha256':backend.BINARY_SHA,'compile_source_sha256':backend.SOURCE_SHA,'compile_verification_sha256':'99fc50814373c96e18254bd130a6b21797276c8a0922fb892782364deb5fafea','compile_verification_report_sha256':'ca0dde6895ef0bcd9f1c2af38ea5c4fa96c47d70defd023b0ea68b64bd3affbd','cpu_commit_sha256':'f3677e9610bea03649fec172b97c0c314f2f2e4c0d40bf9d864df0ec88a44f06','cpu_manifest_sha256':'63f6c842f377fb18738d6016b133c7529803581d0cd661739c0ffd648a82ac54','cpu_verification_sha256':'1c7f2772fb637485020be00f74b6f9295a18ec3d7d10af0587ea350e8756cbc8','cpu_verification_report_sha256':'6c1f43b04f7199176ac21f9367bcb4fee2f6a95924bcb1a968cf70baa61babca','generator_sha256':'746a879192041dee32acb1bcb9360ce9dde6775631c0a0671312660fb71437c8'}
def fs(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def verify_bundle(d):
 r,m,c=(d/n for n in ('result.json','manifest.json','commit.json'))
 if not all(x.is_file() for x in (r,m,c)):raise RuntimeError('core')
 rr,mm,cc=(json.loads(x.read_text()) for x in (r,m,c))
 if rr.get('kind')!='ph1_intel_execution_r1' or mm.get('kind')!='ph1_intel_execution_r1_manifest' or cc!={'kind':'ph1_intel_execution_r1_commit','manifest_sha256':fs(m),'result_sha256':fs(r)}:raise RuntimeError('core_contract')
 if {x['name'] for x in mm['files']}|{'manifest.json','commit.json'}!={p.name for p in d.iterdir()}:raise RuntimeError('exact_set')
 if not all((d/x['name']).stat().st_size==x['bytes'] and fs(d/x['name'])==x['sha256'] for x in mm['files']):raise RuntimeError('file_hash')
 return rr
def configure():base.REPORTS,base.OUT,base.FAILED,base.QUAR,base.verify_bundle=R,OUT,FAILED,QUAR,verify_bundle
def package_exact(root):
 m=json.loads((root/'manifest.json').read_text());c=json.loads((root/'commit.json').read_text());return {p.name for p in root.iterdir()}==({x['name'] for x in m['files']}|{'manifest.json','commit.json'}) and all((root/x['name']).stat().st_size==x['bytes'] and fs(root/x['name'])==x['sha256'] for x in m['files'])
def authorize():
 l=json.loads(LOCK.read_text());obs={'runner_sha256':fs(Path(__file__)),'backend_sha256':fs(Path(backend.__file__)),'common_sha256':fs(Path(common.__file__)),'verifier_sha256':fs(VER),'preflight_sha256':fs(PRE),'prereg_sha256':fs(PR),'audit_sha256':fs(AUD),'compile_commit_sha256':fs(COM/'commit.json'),'compile_result_sha256':fs(COM/'result.json'),'compile_manifest_sha256':fs(COM/'manifest.json'),'compile_build_log_sha256':fs(COM/'intel_build.log'),'compile_binary_sha256':fs(COM/'intel_program.bin'),'compile_source_sha256':fs(COM/'intel_source.cl'),'compile_verification_sha256':fs(CVER),'compile_verification_report_sha256':fs(CREPORT),'cpu_commit_sha256':fs(CPU/'commit.json'),'cpu_manifest_sha256':fs(CPU/'manifest.json'),'cpu_verification_sha256':fs(CPUVER),'cpu_verification_report_sha256':fs(CPUREPORT),'generator_sha256':fs(GEN)}
 if not(l.get('kind')=='ph1_intel_execution_r1_lock' and l.get('execution_open') is True and l.get('audit_token')==ACK and all(l.get(k)==v==EXPECTED.get(k,v) for k,v in obs.items()) and package_exact(COM) and package_exact(CPU) and json.loads(CVER.read_text())['pass'] is True and json.loads(CPUVER.read_text())['pass'] is True):raise RuntimeError('authorization')
 return {'lock_sha256':fs(LOCK),'observed':obs}
def ledger_gates(ev):
 led=ev['ledger'];alloc=[x for x in led if x.get('op')=='host_usm_allocate'];args=[x for x in led if x.get('op')=='set_pointer_arg'];launch=[x for x in led if x.get('op')=='enqueue'];release=[x for x in led if x.get('op')=='release'];finish=[i for i,x in enumerate(led) if x.get('op')=='finish'];reads=[i for i,x in enumerate(led) if x.get('op')=='cpu_direct_read'];expected_release=['usm:'+x[0] for x in reversed(backend.BUFFER_TABLE)]+['kernel:'+x for x in ('down_linear','activation','up_linear','gate_linear')]+['program','queue','context'];expected_args=[(k,i,n) for k,ns in backend.ARGUMENT_MAPS for i,n in enumerate(ns)]
 writes=[x for x in led if x.get('op')=='cpu_direct_write'];inits=[x for x in led if x.get('op')=='initialize'];readrows=[x for x in led if x.get('op')=='cpu_direct_read'];expected_reads=['gate','up','silu','activation','down','gate_counters','up_counters','activation_counters','down_counters'];expected_writes=[('gate_record',common.SPECS[0][7]),('up_record',common.SPECS[1][7]),('down_record',common.SPECS[2][7]),('natural_input',common.INPUT[2]),('silu_lut',common.LUT_SHA)]
 expected_ops=['identity','context_create','queue_create','program_create_binary']+['kernel_create']*4+['host_usm_allocate']*14+['cpu_direct_write']*5+['initialize']*9+['set_pointer_arg']*18+['enqueue']*4+['finish']+['cpu_direct_read']*9+['release']*21+['cleanup']
 return {'identity':ev['identity']['name']=='Intel(R) Arc(TM) Pro 140T GPU (32GB)' and ev['identity']['vendor']=='Intel(R) Corporation' and ev['identity']['driver']=='32.0.101.8517' and ev['identity']['pci']=='0000:00:02.0','compile_identity':ev['source_sha256']==backend.SOURCE_SHA and ev['binary_sha256']==backend.BINARY_SHA,'ledger_order':[x.get('op') for x in led]==expected_ops,'allocations':[(x['name'],x['bytes']) for x in alloc]==list(backend.BUFFER_TABLE) and all(x['type']==backend.r0.CL_MEM_TYPE_HOST_INTEL and x['base']==x['pointer'] and x['queried_size']==x['bytes'] and x['pointer']%4096==0 for x in alloc),'writes':[(x['name'],x['sha256']) for x in writes]==expected_writes,'initialization':[(x['name'],x['value']) for x in inits]==[(x,'ff') for x in ('gate','up','silu','activation','down')]+[(x,'00') for x in ('gate_counters','up_counters','activation_counters','down_counters')],'args':[(x['kernel'],x['index'],x['name']) for x in args]==expected_args and all(x['pointer']==next(a['pointer'] for a in alloc if a['name']==x['name']) for x in args),'launch':[(x['kernel'],x['global'],x['local']) for x in launch]==list(backend.LAUNCHES) and all(x['event_requested'] is False for x in launch),'finish_reads':len(finish)==1 and [x['name'] for x in readrows]==expected_reads and all(i>finish[0] for i in reads) and all(x['after_finish'] is True and x['bytes']==dict(backend.BUFFER_TABLE)[x['name']] and x['sha256']==ev['output_sha256'][x['name']] for x in readrows),'release':[x['name'] for x in release]==expected_release and len(release)==21 and [x['attempt_index'] for x in release]==list(range(21)) and all(x['attempted'] is True and x['code']==0 and x['exception'] is None and x['owned_after'] is False for x in release) and led[-1]['cleanup_complete'] is True and led[-1]['release_attempts']==21 and led[-1]['live_owned_resources']==0 and led[-1]['live_resource_names']==[],'extensions':ev['extension_counts']=={'clHostMemAllocINTEL':14,'clMemFreeINTEL':14,'clSetKernelArgMemPointerINTEL':18,'clGetMemAllocInfoINTEL':42},'forbidden':set(ev['forbidden_calls'])==set(backend.FORBIDDEN) and all(v==0 for v in ev['forbidden_calls'].values())}
def main():
 p=argparse.ArgumentParser();p.add_argument('--ack',required=True);a=p.parse_args()
 if a.ack!=ACK:raise SystemExit('ack')
 auth=authorize();configure();existing=base.recover()
 if existing['already']:
  positive=existing['result'].get('positive') is True;print(json.dumps({'status':'already_complete','positive':positive}));return 0 if positive else 3
 import psutil
 start=psutil.virtual_memory().available;proc=psutil.Process();peak=proc.memory_info().peak_wset
 if start<16*2**30:raise RuntimeError('start_ram')
 records,inp,lut,controls=common.package();post_payload=psutil.virtual_memory().available;peak=max(peak,proc.memory_info().peak_wset)
 if post_payload<2*2**30 or peak>12*2**30:raise RuntimeError('resource_predevice')
 attempt=R/(OUT.name+'.'+uuid.uuid4().hex+'.inprogress');attempt.mkdir();opened=False
 try:
  opened=True;ev=backend.Backend().run(records,inp,lut,auth);lg=ledger_gates(ev);outs={k:bytes.fromhex(v) for k,v in ev['outputs'].items()};stages={k:common.sha(outs[k]) for k in ('gate','up','silu','activation','down')};expected={'gate':'e8a00c17f2ea66f4fc933103eeaf2429c9c1b63fd903720eabaa5b7513acc867','up':'f8dc1dc2c9f19e2012ce806ea121d07135e70d383354ff8faa777377595def08','silu':'a83041f1517b31f6b2a81b5d98c3f9a128b5bdc5602b57000453a57b036295e8','activation':'762384a50598dc67aca0963b1e9ed52f5eda71ec9643aeb18a6750ab92fe3d5f','down':'142607c8defe588a2833ce65a774515aeb9691dd7008e4ff6b32488af9bf10fc'};counter=all(all(int.from_bytes(outs[k][i:i+4],'little')==1 for i in range(0,len(outs[k]),4)) for k in ('gate_counters','up_counters','activation_counters','down_counters'));peak=max(peak,proc.memory_info().peak_wset);final=psutil.virtual_memory().available;resource={'start_available':start,'post_payload_available':post_payload,'final_available':final,'post_serialize_available':None,'peak_wset':peak};gates={'controls':len(controls)==22 and all(x['pass'] and all(v==0 for v in x['predevice_counts'].values()) for x in controls),'stages':stages==expected,'counters':counter,**lg,'resources':final>=2*2**30 and peak<=12*2**30};result={'kind':'ph1_intel_execution_r1','status':'intel_execution_positive' if all(gates.values()) else 'intel_execution_negative','positive':all(gates.values()),'authorization':auth,'controls':controls,'resource':resource,'gates':gates,'evidence':ev,'stage_hashes':stages,'claim':'one real expert/input Intel correctness component only'};_draft=base.canon(result);post_serialize=psutil.virtual_memory().available;peak=max(peak,proc.memory_info().peak_wset);resource['post_serialize_available']=post_serialize;resource['peak_wset']=peak;gates['resources']=gates['resources'] and post_serialize>=2*2**30 and peak<=12*2**30;result['positive']=all(gates.values());result['status']='intel_execution_positive' if result['positive'] else 'intel_execution_negative';base.write(attempt/'result.json',base.canon(result));files=[{'name':x.name,'bytes':x.stat().st_size,'sha256':fs(x)} for x in attempt.iterdir()];base.write(attempt/'manifest.json',base.canon({'kind':'ph1_intel_execution_r1_manifest','files':files}));base.write(attempt/'commit.json',base.canon({'kind':'ph1_intel_execution_r1_commit','manifest_sha256':fs(attempt/'manifest.json'),'result_sha256':fs(attempt/'result.json')}));artifact=sum(x.stat().st_size for x in attempt.iterdir())
  if artifact>16*2**20:raise RuntimeError('artifact_cap')
  verify_bundle(attempt);base.move(attempt,OUT);verify_bundle(OUT);print(json.dumps({'status':result['status'],'positive':result['positive'],'artifact_bytes':artifact}));return 0 if result['positive'] else 3
 except Exception as e:base.archive(FAILED,'attempt',{'kind':'ph1_intel_execution_r1_failure','error':f'{type(e).__name__}:{e}','traceback':traceback.format_exc(),'device_opened':opened,'backend_evidence':getattr(e,'evidence',None)},attempt if attempt.exists() else (OUT if OUT.exists() else None));return 3
if __name__=='__main__':raise SystemExit(main())
