#!/usr/bin/env python3
"""R8A fresh physical authorization after independently verified R8P8."""
from __future__ import annotations

import ctypes as C, hashlib, json, os, sys, traceback, uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]; S = ROOT / "scripts/streamq5_moe"; R = ROOT / "reports/streamq5_moe"; sys.path.insert(0, str(S))
import run_het_next_l0_ph1_intel_execution_r7a as physical

SCRIPT = Path(__file__).resolve(); VERIFIER = S / "verify_het_next_l0_ph1_intel_execution_r8a.py"; PREREG = R / "HET_NEXT_L0_PH1_INTEL_EXECUTION_R8A_PREREGISTRATION_2026-08-14.md"; LOCK = R / "het_next_l0_ph1_intel_execution_r8a_lock.json"
OUT = R / "het_next_l0_ph1_intel_execution_r8a"; BACKEND_FAILED = R / "het_next_l0_ph1_intel_execution_r8a_backend_failed_attempts"; BACKEND_QUARANTINE = R / "het_next_l0_ph1_intel_execution_r8a_backend_quarantine"; FAILED = R / "het_next_l0_ph1_intel_execution_r8a_failed_attempts"; QUARANTINE = R / "het_next_l0_ph1_intel_execution_r8a_quarantine"; VERIFY_RESULT = R / "het_next_l0_ph1_intel_execution_r8a_independent_verification.json"
ACK = "PH1_INTEL_EXECUTION_R8A_AFTER_R8P8_PASS_AND_SOURCE_AUDIT_GO"; MAX_FAILURE_BYTES = 16 * 2**20
VENV = ROOT / ".venv"; VENV_PYTHON = VENV / "Scripts/python.exe"; PYVENV = VENV / "pyvenv.cfg"; ALIAS = Path(r"C:\Users\de_do\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe"); BASE_PREFIX = Path(r"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0")
EXPECTED_NATIVE = [str(ALIAS), "-I", "-B", str(SCRIPT), "--ack", ACK]; EXPECTED_ARGV = [str(SCRIPT), "--ack", ACK]
R8P8_RESULT = R / "het_next_l0_ph1_intel_execution_r8p8_static_preflight.json"; R8P8_MANIFEST = R / "het_next_l0_ph1_intel_execution_r8p8_static_preflight.manifest.json"; R8P8_COMMIT = R / "het_next_l0_ph1_intel_execution_r8p8_static_preflight.commit.json"; R8P8_VERIFY = R / "het_next_l0_ph1_intel_execution_r8p8_independent_verification.json"; R8P8_AUDIT = R / "HET_NEXT_L0_PH1_INTEL_EXECUTION_R8P8_INDEPENDENT_SOURCE_AUDIT_2026-08-14.md"; R8P8_LOCK = R / "het_next_l0_ph1_intel_execution_r8p8_lock.json"
R7D_LOCK = R / "het_next_l0_ph1_intel_execution_r7d_lock.json"; R7C2_RESULT = R / "het_next_l0_ph1_intel_execution_r7c2_static_preflight.json"; R7A_RESULT = R / "het_next_l0_ph1_intel_execution_r7a_authorization_preflight.json"; R7P_RESULT = R / "het_next_l0_ph1_intel_execution_r7p_static_preflight.json"; R7A_VERIFICATION = R / "het_next_l0_ph1_intel_execution_r7a_independent_verification.json"
R7D1_FAILURE_ROOT = R / "het_next_l0_ph1_intel_execution_r7d1_failed_attempts"; R7D1_FAILURE = R7D1_FAILURE_ROOT / "attempt_7c45ba0bda09470eba7145ef75281ea3/failure.json"; R7D1_DIAGNOSIS = R / "HET_NEXT_L0_PH1_INTEL_EXECUTION_R7D1_PSUTIL_FAILURE_AND_R8_RUNTIME_REPAIR_AUDIT_2026-08-14.md"; R8P6_FAILURE_ROOT = R / "het_next_l0_ph1_intel_execution_r8p6_failed_attempts"; R8P6_FAILURE = R8P6_FAILURE_ROOT / "attempt_71e198678f004a56a6912d07a4187dfd/failure.json"; R8P6_DIAGNOSIS = R / "HET_NEXT_L0_PH1_INTEL_EXECUTION_R8P6_DIRECT_ENTRY_FAILURE_DIAGNOSIS_2026-08-14.md"
R8P8_SHA = "5e77ef9fd4d5a374bc56fd51707ba6bb1a5353e9276a96d3190af589d1d636b0"; R8P8_MANIFEST_SHA = "b6b702846753ffc32dd94802752d847284a16ddf9a6a530047544febbe025a34"; R8P8_COMMIT_SHA = "4431a49104e46384ca8927b5a38e6c85e3d729ca2565c7474cbfc623cd9b3a89"; R8P8_VERIFY_SHA = "577881b17a47b2d1208687192ff0582d2bfcfa36c84e7abd85ffe38a769148c8"; PREPARATION_SHA = "f5a15db125c7a69357574111bd9549c36ae74b67af12205fc71a99a4c8962a49"; R7C2_SHA = "de8745c02cd0b2951adbb04338cf350704608023530edd91a260b73880ebcd8c"; R7A_SHA = "a5b8e70cd40e241e16a250347cf06258a6540100f40423bc7216cb3639191265"; R7P_SHA = "e10c513fdbecb27e08319c462ba1d1020b1c94c4ff5d9199047ae513197dd959"
R8P8_CHECKS = {"base_clean", "closed_pending", "cpu_preparation", "current_transactions", "entry_mutations", "explicit_topology", "failure_simulation", "hash_bindings", "local_entry_identity", "r7d1_failure", "r8p6_failure", "runtime", "runtime_lock", "runtime_mutations", "start_ram", "static_boundary", "topology", "wheel_records"}; R8P8_VERIFY_CHECKS = {"bundle", "explicit_topology", "independent_output_transactions", "live_identity", "live_identity_mutations", "lock", "preparation", "r8p6_failure", "result", "result_mutations", "runtime", "static_boundary", "topology", "wheel_records"}
R7C2_CHECKS = {"auth_result_exact", "candidate_import_free", "clean_state_complete", "closed_pending", "device_opened_exact", "extension_mutations", "hash_bindings", "inherited_r7c1_cases", "no_device_static"}; R7A_CHECKS = {"authorization_only_runner", "fixed_verifier_unchanged", "hash_bindings", "no_device_static", "open_exact", "output_absent", "r7p_pass18"}
R7P_MUTATIONS = ("getinfo_status", "setptr_status", "ownership_missing", "ownership_duplicate", "ownership_return", "ownership_pending", "ownership_pointer", "identity", "control_missing", "output", "pointer_alias", "alignment", "usm_type", "usm_base", "arg_pointer", "launch_geometry", "launch_event", "read_order", "release_order", "release_owned", "release_code", "cleanup", "provenance", "resource_summary", "resource_order", "resource_peak", "forbidden_api", "stage_hash")
CHAIN = {"runner_sha256": SCRIPT, "verifier_sha256": VERIFIER, "prereg_sha256": PREREG, "r8p8_result_sha256": R8P8_RESULT, "r8p8_manifest_sha256": R8P8_MANIFEST, "r8p8_commit_sha256": R8P8_COMMIT, "r8p8_verification_sha256": R8P8_VERIFY, "r8p8_audit_sha256": R8P8_AUDIT, "r8p8_lock_sha256": R8P8_LOCK, "r7d_runner_sha256": S / "run_het_next_l0_ph1_intel_execution_r7d.py", "r7d_verifier_sha256": S / "verify_het_next_l0_ph1_intel_execution_r7d.py", "r7d_lock_sha256": R7D_LOCK, "r7c2_result_sha256": R7C2_RESULT, "r7a_result_sha256": R7A_RESULT, "r7p_result_sha256": R7P_RESULT, "r7d1_failure_sha256": R7D1_FAILURE, "r7d1_diagnosis_sha256": R7D1_DIAGNOSIS, "r8p6_failure_sha256": R8P6_FAILURE, "r8p6_diagnosis_sha256": R8P6_DIAGNOSIS, "physical_runner_sha256": Path(physical.__file__), "physical_verifier_sha256": S / "verify_het_next_l0_ph1_intel_execution_r7a.py", "backend_sha256": S / "het_next_l0_ph1_intel_execution_r6_backend.py", "common_sha256": S / "het_next_l0_ph1_intel_execution_r6_common.py"}
R7D_CHAIN = {
    "runner_sha256": S/"run_het_next_l0_ph1_intel_execution_r7d.py", "verifier_sha256": S/"verify_het_next_l0_ph1_intel_execution_r7d.py", "prereg_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7D_PREREGISTRATION_2026-08-14.md",
    "r7c2_runner_sha256": S/"run_het_next_l0_ph1_intel_execution_r7c2.py", "r7c2_verifier_sha256": S/"verify_het_next_l0_ph1_intel_execution_r7c2.py", "r7c2_preflight_sha256": S/"preflight_het_next_l0_ph1_intel_execution_r7c2.py", "r7c2_prereg_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7C2_PREREGISTRATION_2026-08-14.md", "r7c2_lock_sha256": R/"het_next_l0_ph1_intel_execution_r7c2_lock.json", "r7c2_audit_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7C2_INDEPENDENT_SOURCE_AUDIT_2026-08-14.md", "r7c2_result_sha256": R7C2_RESULT,
    "r7c1_runner_sha256": S/"run_het_next_l0_ph1_intel_execution_r7c1.py", "r7c1_verifier_sha256": S/"verify_het_next_l0_ph1_intel_execution_r7c1.py", "r7c1_preflight_sha256": S/"preflight_het_next_l0_ph1_intel_execution_r7c1.py", "r7c1_prereg_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7C1_PREREGISTRATION_2026-08-14.md", "r7c1_lock_sha256": R/"het_next_l0_ph1_intel_execution_r7c1_lock.json", "r7c1_audit_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7C1_INDEPENDENT_SOURCE_AUDIT_2026-08-14.md",
    "r7c_runner_sha256": S/"run_het_next_l0_ph1_intel_execution_r7c.py", "r7c_verifier_sha256": S/"verify_het_next_l0_ph1_intel_execution_r7c.py", "r7c_preflight_sha256": S/"preflight_het_next_l0_ph1_intel_execution_r7c.py", "r7c_prereg_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7C_PREREGISTRATION_2026-08-14.md", "r7c_lock_sha256": R/"het_next_l0_ph1_intel_execution_r7c_lock.json", "r7c_audit_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7C_INDEPENDENT_SOURCE_AUDIT_2026-08-14.md",
    "r7b_runner_sha256": S/"run_het_next_l0_ph1_intel_execution_r7b.py", "r7b_verifier_sha256": S/"verify_het_next_l0_ph1_intel_execution_r7b.py", "r7b_prereg_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7B_PREREGISTRATION_2026-08-14.md", "r7b_lock_sha256": R/"het_next_l0_ph1_intel_execution_r7b_lock.json", "r7b_audit_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7B_INDEPENDENT_SOURCE_AUDIT_2026-08-14.md",
    "physical_runner_sha256": S/"run_het_next_l0_ph1_intel_execution_r7a.py", "physical_verifier_sha256": S/"verify_het_next_l0_ph1_intel_execution_r7a.py", "physical_preflight_sha256": S/"preflight_het_next_l0_ph1_intel_execution_r7a.py", "physical_prereg_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7A_PREREGISTRATION_2026-08-14.md", "physical_lock_sha256": R/"het_next_l0_ph1_intel_execution_r7a_lock.json", "authorization_result_sha256": R7A_RESULT, "r7a_audit_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7A_INDEPENDENT_SOURCE_AUDIT_2026-08-14.md",
    "r7p_preflight_sha256": S/"preflight_het_next_l0_ph1_intel_execution_r7p.py", "r7p_lock_sha256": R/"het_next_l0_ph1_intel_execution_r7p_lock.json", "r7p_prereg_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7P_PREREGISTRATION_2026-08-14.md", "r7p_audit_sha256": R/"HET_NEXT_L0_PH1_INTEL_EXECUTION_R7P_INDEPENDENT_SOURCE_AUDIT_2026-08-14.md", "r7p_result_sha256": R7P_RESULT,
    "backend_sha256": S/"het_next_l0_ph1_intel_execution_r6_backend.py", "common_sha256": S/"het_next_l0_ph1_intel_execution_r6_common.py", "r0_backend_sha256": S/"het_next_l0_ph1_intel_execution_r0_backend.py", "r0_runner_sha256": S/"run_het_next_l0_ph1_intel_execution_r0.py",
}

def sha256(path: Path) -> str: return hashlib.sha256(path.read_bytes()).hexdigest()
def canonical(x: object) -> bytes: return (json.dumps(x, sort_keys=True, separators=(",", ":")) + "\n").encode()
def same(a: object, b: object) -> bool: return isinstance(a, str) and isinstance(b, str) and a.casefold() == b.casefold()
def parse_commandline(raw: str) -> list[str]:
    k = C.WinDLL("kernel32", use_last_error=True); s = C.WinDLL("shell32", use_last_error=True); parse = s.CommandLineToArgvW; parse.argtypes = (C.c_wchar_p, C.POINTER(C.c_int)); parse.restype = C.POINTER(C.c_wchar_p); free = k.LocalFree; free.argtypes = (C.c_void_p,); free.restype = C.c_void_p; n = C.c_int(); ptr = parse(raw, C.byref(n))
    if not ptr: raise C.WinError(C.get_last_error())
    try: return [ptr[i] for i in range(n.value)]
    finally:
        if free(C.cast(ptr, C.c_void_p)): raise C.WinError(C.get_last_error())
def invocation() -> dict:
    k = C.WinDLL("kernel32", use_last_error=True); get = k.GetCommandLineW; get.argtypes = (); get.restype = C.c_wchar_p; raw = get()
    return {"native_raw": raw, "native_argv": parse_commandline(raw), "orig_argv": list(sys.orig_argv), "argv": list(sys.argv), "sys_executable": sys.executable, "sys_prefix": sys.prefix, "base_executable": getattr(sys, "_base_executable", None), "base_prefix": sys.base_prefix, "isolated": sys.flags.isolated, "dont_write_bytecode": sys.dont_write_bytecode, "python_sha256": sha256(VENV_PYTHON), "pyvenv_sha256": sha256(PYVENV), "direct_entry": __name__ == "__main__" and __spec__ is None and __package__ in (None, "") and Path(__file__).resolve() == SCRIPT}
def invocation_valid(x: dict) -> bool:
    return set(x) == {"native_raw", "native_argv", "orig_argv", "argv", "sys_executable", "sys_prefix", "base_executable", "base_prefix", "isolated", "dont_write_bytecode", "python_sha256", "pyvenv_sha256", "direct_entry"} and parse_commandline(x["native_raw"]) == EXPECTED_NATIVE and x["native_argv"] == x["orig_argv"] == EXPECTED_NATIVE and x["argv"] == EXPECTED_ARGV and same(x["sys_executable"], str(VENV_PYTHON.resolve())) and same(x["sys_prefix"], str(VENV.resolve())) and same(x["base_executable"], str(ALIAS)) and same(x["base_prefix"], str(BASE_PREFIX)) and x["isolated"] == 1 and x["dont_write_bytecode"] is True and x["python_sha256"] == "0b471133e110cfb53a061cad528ce8e517d7b9ac41a0a396c39ad795a487fc14" and x["pyvenv_sha256"] == "9b87fd6636e0e8d878f584a49e365b5e9bdc75507be16f018ee535a69ee1e8fe" and x["direct_entry"] is True

def r7p_pass18(x: dict) -> bool:
    f = x.get("verifier_fixture_evidence", {}); linear = x.get("linear_sentinel", {}).get("shapes", {}); neg = x.get("write_after_loop_negative", {}); checks = x.get("checks", {})
    return x.get("kind") == "ph1_intel_execution_r7p_static_preflight" and x.get("pass") is True and x.get("passed") == x.get("total") == 18 and x.get("no_payload_compiler_device") is True and len(checks) == 18 and all(v is True for v in checks.values()) and len(f.get("baseline_checks", {})) == 20 and all(v is True for v in f["baseline_checks"].values()) and f.get("baseline_false_names") == [] and tuple(f.get("mutation_names", ())) == R7P_MUTATIONS == tuple(f.get("rejected_mutations", ())) and set(linear) == {"gate_up", "down"} and all(r.get("all_rows_equal") is True and r.get("repeat_equal") is True and r.get("first_sha256") == r.get("expected_sha256") == r.get("second_sha256") for r in linear.values()) and neg.get("pass") is True and neg.get("r7_assignment_inside_row_loop") is True and neg.get("mutant_assignment_inside_row_loop") is False and all(r.get("poison_prefix") is True and r.get("last_correct") is True and r.get("repeat_equal") is True and r.get("differs_from_target") is True for r in neg.get("shapes", {}).values())
def r7a_pass7(x: dict) -> bool:
    c = x.get("checks", {}); return set(x) == {"ack", "checks", "kind", "no_payload_compiler_device", "pass", "passed", "r7p_result_sha256", "total"} and x.get("kind") == "ph1_intel_execution_r7a_authorization_preflight" and x.get("pass") is True and x.get("passed") == x.get("total") == 7 and x.get("no_payload_compiler_device") is True and x.get("r7p_result_sha256") == R7P_SHA and set(c) == R7A_CHECKS and all(v is True for v in c.values())
def r7c2_pass9(x: dict) -> bool:
    c = x.get("checks", {}); clean = x.get("clean_state", {}); return set(x) == {"checks", "clean_state", "device_opened_cases", "inherited_cases", "kind", "no_payload_compiler_device", "pass", "passed", "rejected_extension_mutations", "total"} and x.get("kind") == "ph1_intel_execution_r7c2_static_preflight" and x.get("pass") is True and x.get("passed") == x.get("total") == 9 and x.get("no_payload_compiler_device") is True and set(c) == R7C2_CHECKS and all(v is True for v in c.values()) and len(x.get("inherited_cases", {})) == 9 and all(v is True for v in x["inherited_cases"].values()) and x.get("device_opened_cases") == {"false_retained": True, "true_retained": True, "wrong_type_rejected": True} and x.get("rejected_extension_mutations") == ["token", "result_hash", "check_false", "observed_missing", "lock_hash", "lock_closed", "r7p", "stages"] and all(v is True for section in (clean.get("required", {}), clean.get("absent", {}), clean.get("glob_empty", {})) for v in section.values()) and all(v == [] for v in clean.get("glob_paths", {}).values())
def r8p8_pass() -> bool:
    if [sha256(p) for p in (R8P8_RESULT, R8P8_MANIFEST, R8P8_COMMIT, R8P8_VERIFY)] != [R8P8_SHA, R8P8_MANIFEST_SHA, R8P8_COMMIT_SHA, R8P8_VERIFY_SHA]: return False
    rb = R8P8_RESULT.read_bytes(); mb = R8P8_MANIFEST.read_bytes(); row = json.loads(rb); manifest = json.loads(mb); commit = json.loads(R8P8_COMMIT.read_text()); verification = json.loads(R8P8_VERIFY.read_text())
    bundle = manifest == {"files": [{"bytes": len(rb), "name": R8P8_RESULT.name, "sha256": R8P8_SHA}], "kind": "ph1_intel_execution_r8p8_static_preflight_manifest"} and commit == {"kind": "ph1_intel_execution_r8p8_static_preflight_commit", "manifest_sha256": R8P8_MANIFEST_SHA, "result_sha256": R8P8_SHA}
    return bundle and row.get("kind") == "ph1_intel_execution_r8p8_static_preflight" and row.get("pass") is True and row.get("passed") == row.get("total") == 18 and set(row.get("checks", {})) == R8P8_CHECKS and all(v is True for v in row["checks"].values()) and row.get("preparation_digest") == PREPARATION_SHA and row.get("model_forward") is row.get("compiler_opened") is row.get("opencl_opened") is row.get("device_opened") is False and verification.get("kind") == "ph1_intel_execution_r8p8_independent_verification" and verification.get("pass") is True and verification.get("passed") == verification.get("total") == 14 and set(verification.get("checks", {})) == R8P8_VERIFY_CHECKS and all(v is True for v in verification["checks"].values()) and verification.get("result_sha256") == R8P8_SHA and verification.get("manifest_sha256") == R8P8_MANIFEST_SHA and verification.get("commit_sha256") == R8P8_COMMIT_SHA and verification.get("model_forward") is verification.get("compiler_opened") is verification.get("opencl_opened") is verification.get("device_opened") is False
def exact_failure(root: Path, path: Path, digest: str, kind: str) -> bool:
    files = sorted(p.resolve() for p in root.rglob("*") if p.is_file()); dirs = sorted(p.resolve() for p in root.iterdir() if p.is_dir()) if root.exists() else []; row = json.loads(path.read_text()) if files == [path.resolve()] and sha256(path) == digest else {}
    expected_size = 931 if digest.startswith("88335dc0") else 2986
    return len(dirs) == 1 and files == [path.resolve()] and path.stat().st_size == expected_size and row.get("kind") == kind and row.get("device_opened") is False and isinstance(row.get("error"), str) and row.get("status") in ("valid_negative_failure", "valid_protocol_negative")
def r7d_contract() -> bool:
    if sha256(R7D_LOCK) != "fa2a514af78ac75cd94376f8d04d801fd1dfa27592b595bf42a662bab3e15658": return False
    lock = json.loads(R7D_LOCK.read_text()); observed = {k: sha256(v) for k,v in R7D_CHAIN.items()}; r7c2 = json.loads(R7C2_RESULT.read_text()); r7a = json.loads(R7A_RESULT.read_text()); r7p = json.loads(R7P_RESULT.read_text())
    return set(lock) == {"kind", "execution_open", "audit_token", "physical_output", "physical_verifier", *observed} and lock.get("kind") == "ph1_intel_execution_r7d_lock" and lock.get("execution_open") is True and lock.get("audit_token") == "PH1_INTEL_EXECUTION_R7D_AFTER_R7C2_PASS9_AND_FINAL_AUDIT_GO" and lock.get("physical_output") == "het_next_l0_ph1_intel_execution_r7a" and lock.get("physical_verifier") == "verify_het_next_l0_ph1_intel_execution_r7d.py" and all(lock.get(k) == v for k,v in observed.items()) and observed["r7c2_result_sha256"] == R7C2_SHA and observed["authorization_result_sha256"] == R7A_SHA and observed["r7p_result_sha256"] == R7P_SHA and observed["physical_runner_sha256"] == "01fa21266137335494de2d21adba11f45fe83ff95f660d90cef7acc389c1cb04" and observed["physical_verifier_sha256"] == "18b64765469e38c5211d28afe586e0a559e97f6e2110f09f54c4f58d9c38dd88" and r7c2_pass9(r7c2) and r7a_pass7(r7a) and r7p_pass18(r7p) and not R7A_VERIFICATION.exists()
def clean_now() -> bool:
    paths = (OUT, BACKEND_FAILED, BACKEND_QUARANTINE, FAILED, QUARANTINE, VERIFY_RESULT); stale = list(R.glob("het_next_l0_ph1_intel_execution_r8a*.inprogress*")); return all(not p.exists() for p in paths) and stale == []
def authorize() -> dict:
    ident = invocation()
    if not invocation_valid(ident) or not clean_now(): raise RuntimeError("invocation_or_clean")
    observed = {k: sha256(v) for k, v in CHAIN.items()}; lock = json.loads(LOCK.read_text())
    if not (set(lock) == {"kind", "execution_open", "audit_token", "one_attempt", *observed} and lock.get("kind") == "ph1_intel_execution_r8a_lock" and lock.get("execution_open") is True and lock.get("audit_token") == ACK and lock.get("one_attempt") is True and all(lock.get(k) == v for k, v in observed.items()) and r8p8_pass() and r7d_contract() and exact_failure(R7D1_FAILURE_ROOT, R7D1_FAILURE, "88335dc0c7d712d0c2a19a9ee51fe5959f3d725daf2f10d00b8c4a1d9069e3a0", "ph1_intel_execution_r7c2_failure") and exact_failure(R8P6_FAILURE_ROOT, R8P6_FAILURE, "03e48ed76dd848f0c1e993f8452245917115b1b8fb22596871dd933e4758b372", "ph1_intel_execution_r8p6_failure")): raise RuntimeError("authorization")
    inherited = physical.authorize(); inherited["r8a_authorization"] = {"lock_sha256": sha256(LOCK), "observed": observed, "audit_token": ACK, "invocation": ident, "r8p8_pass": True, "r7d_contract": True, "r7a_verification_absent": True, "r7d1_failure_sha256": observed["r7d1_failure_sha256"], "r8p6_failure_sha256": observed["r8p6_failure_sha256"]}; return inherited

def configure() -> None:
    physical.OUT = OUT; physical.FAILED = BACKEND_FAILED; physical.QUAR = BACKEND_QUARANTINE
def failure_paths() -> set[Path]: return {p.resolve() for p in BACKEND_FAILED.glob("*/failure.json")} if BACKEND_FAILED.exists() else set()
def committed() -> dict | None:
    try: return physical.verify_bundle(OUT) if OUT.exists() else None
    except Exception: return None
def atomic_summary(payload: dict) -> Path:
    data = canonical(payload)
    if len(data) > MAX_FAILURE_BYTES: data = canonical({"kind": "ph1_intel_execution_r8a_failure", "status": "valid_negative_failure", "stage": payload.get("stage"), "error": "failure_evidence_oversize", "original_bytes": len(data), "original_sha256": hashlib.sha256(data).hexdigest(), "device_opened": bool(payload.get("device_opened", False)), "disposition": "bounded_summary_only"})
    FAILED.mkdir(parents=True, exist_ok=True); nonce = uuid.uuid4().hex; temp = R / f"{FAILED.name}.{nonce}.inprogress"; dest = FAILED / f"attempt_{nonce}"; temp.mkdir()
    try: physical.base.write(temp / "failure.json", data); physical.base.move(temp, dest)
    except Exception:
        if temp.exists(): QUARANTINE.mkdir(parents=True, exist_ok=True); physical.base.move(temp, QUARANTINE / f"failed_commit_{nonce}")
        raise
    return dest
def inherited_evidence(path: Path) -> tuple[bool, dict]:
    files = sorted(p for p in path.parent.rglob("*") if p.is_file()); total = sum(p.stat().st_size for p in files); row = json.loads(path.read_text()) if len(files) <= 32 and total <= MAX_FAILURE_BYTES else {}; valid = row.get("kind") == "ph1_intel_execution_r7a_failure" and row.get("status") == "valid_negative_failure" and isinstance(row.get("device_opened"), bool) and isinstance(row.get("error"), str)
    return valid, {"failure_sha256": sha256(path), "bundle_bytes": total, "file_count": len(files), "device_opened": row.get("device_opened"), "valid": valid}
def outer_execute(auth: dict) -> int:
    before = failure_paths()
    try: code = physical.execute_authorized(auth)
    except Exception as exc:
        result = committed()
        if result is not None: return 0 if result.get("positive") is True else 3
        atomic_summary({"kind": "ph1_intel_execution_r8a_failure", "status": "valid_negative_failure", "stage": "outer_boundary", "error": f"{type(exc).__name__}:{exc}"[:2048], "traceback": traceback.format_exc()[-32768:], "device_opened": bool(getattr(exc, "device_opened", False)), "disposition": "atomic_create_new_bounded_outer_failure"}); return 3
    result = committed()
    if result is not None: return 0 if result.get("positive") is True else 3
    new = sorted(failure_paths() - before); rows = []
    for p in new:
        try: ok, evidence = inherited_evidence(p)
        except Exception as exc: ok, evidence = False, {"valid": False, "error": type(exc).__name__}
        rows.append({"valid": ok, **evidence})
    valid = len(rows) == 1 and rows[0]["valid"] is True; atomic_summary({"kind": "ph1_intel_execution_r8a_failure", "status": "valid_negative_failure", "stage": "delegated_nonzero" if code else "delegated_invalid_success", "error": "delegated_execution_nonzero" if code else "success_without_commit", "delegated_return": code, "device_opened": any(x.get("device_opened") is True for x in rows), "new_inherited_failure_count": len(rows), "inherited_evidence_valid": valid, "inherited": rows, "disposition": "atomic_bounded_digest_summary"}); return 3
def main() -> int:
    if sys.argv != EXPECTED_ARGV: return 3
    try: auth = authorize()
    except Exception: return 3
    configure(); return outer_execute(auth)
if __name__ == "__main__": raise SystemExit(main())
